### ISSUE TITLE
Project health?

### ISSUE THREAD

**Issue by fuzzy76** [pydanny/django-wysiwyg#62]
Can't help noticing the user account that owns this repository has been renamed from "pydanny" to "pydanny-archive" and the projects haven't seen a commit in almost a year. Is this project still alive?

**Comment by pydanny** [comment]
I'm not maintaining this project anymore.

If someone else wants to take over this project, then it will be maintained. I'll let @acdha and @vdboor have the first chance because they also have commit rights.

In the meantime, I'll put a notice in the README that this project is unmaintained.

**Comment by pydanny** [comment]
Just added a note in the README to reflect that this project is unmaintained. In that note I explain how to get the project maintained again.
